#select theme
#theme: jekyll-text-theme #, just-the-docs, minimal-mistakes-jekyll # for github supported theme, replacing THEME-NAME with the name of the theme as shown in the _config.yml of the theme's repository. 
remote_theme: adamrehn/jekyll-theme-gitbook@v0.0.6 #, alertbox/bookworm, sighingnow/jekyll-gitbook, jasongrimes/jekyll-chapterbook #for other theme hosted on github, replacing THEME-NAME with the name of the theme as shown in the README of the theme's repository. 
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
exclude: [".gitignore", "LICENSE", "README.md"]
sass:
  style: compressed

title: "Freedom Highway" #[The title of your site]
description: "A repository of information" #[A short description of your site's purpose]

#adamrehn theme config
theme-settings:
  collection: "categories" # The name of the Jekyll collection that contains the site's chapters (REQUIRED)
  navigation: # Navigation menu settings (OPTIONAL, only needed if you want to override the defaults)
    # Specifies whether navigation links should be generated for chapter index files that use the `chapter-index` layout (OPTIONAL, defaults to false)
    indices: false
    # Specifies whether the navigation links for each chapter should be output as collapsible sections using HTML <detail> tags, with chapter headings as <summary> tags (OPTIONAL, defaults to false)
    collapsible: false
    # When collapsible sections are enabled, specifies whether sections are collapsed by default (OPTIONAL, defaults to false)
    collapsed: false
  copyright: # Copyright settings for the page footer (REQUIRED)
    author: "Big Mog & Little Mog"
    year: 2025
    license: "CC BY 4.0"
  # Override the path to the site's logo image (OPTIONAL, defaults to "/assets/images/logo.svg")
  #logo: "/path/to/logo.png"
  # Override the path to the site's Open Graph image (OPTIONAL, defaults to "/assets/images/opengraph.png")
  #opengraph: "/path/to/opengraph.png"
  # Favicon settings (OPTIONAL, only needed if you want to override the defaults)
  #favicon:
    # Override the PNG version of the favicon (OPTIONAL, defaults to "/assets/images/favicon.png")
    #png: "/path/to/favicon.png"
    # Override the SVG version of the favicon (OPTIONAL, defaults to "/assets/images/favicon.svg")
    #svg: "/path/to/favicon.svg"
  # Font Awesome icon settings (OPTIONAL, only needed if you want to override the defaults)
  #fontawesome:
    # Specify that you are providing Font Awesome through your own CSS (OPTIONAL, defaults to false)
    #local: true
    # Specify a Font Awesome Kit URL to provide icons (OPTIONAL, defaults to none, takes precedence over "local" if both are specified)
    #kit: "https://kit.fontawesome.com/xxxxxxxxxx.js"
    # Override individual Font Awesome icons (OPTIONAL, only needed if you want to override the defaults)
    #icons:
      # Override the "return to top" icon (OPTIONAL, defaults to "fa-arrow-up")
      # (Incidentally, if you do have a Font Awesome Pro license then this particular icon override is highly recommended)
      #top: "fa-arrow-alt-to-top"
      # Other icon overrides go here (see the full list of supported overrides below)
      # ...
toc: true
# Configure the permalinks for each category ("chapter" from the theme's perspective)
collections_dir: #_collections
collections:
  categories:
    output: true
    permalink: /:path
# Use front matter defaults to supply the metadata for each category
defaults:
  -
    scope:
      path: ""
      type: "sections"
    values:
      # Use the "default" layout provided by the theme for all pages
      layout: "default"
  -
    scope:
      # This is the filesystem path for the subdirectory containing the category's pages
      path: #"_collections/_categories/basic"
    values:
      # The chapter name and number are required
      chapter: "Basic"
      chapnum: 1
      # An icon is optional and will be displayed next to the chapter name if specified
      #icon: "fas fa-school"
  #-
    #scope:
    #  path: "_collections/_categories/intermediate"
    #values:
    #  chapter: "Intermediate"
    #  chapnum: 2
    #  icon: "fas fa-university"
  #-
    #scope:
    #  path: "_collections/_categories/advanced"
    #values:
    #  chapter: "Advanced"
    #  chapnum: 3
    #  icon: "fas fa-graduation-cap"
